# Numpy Array Basics
### Learn Numpy with proper Basics

### Importing Numpy

In [2]:
import numpy as np
import time

### Creating Array Using Numpy in Python

In [2]:
arr_1D = np.array([1, 2, 3, 4, 5])
print(arr_1D)
print("BaseExceptionGroup\n")
arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2D)

[1 2 3 4 5]
BaseExceptionGroup

[[1 2 3]
 [4 5 6]]


In [3]:
arr =np.array([[6, 7, 8, 9, 10],[1, 2, 3, 4, 5]])
print("Array:", arr)
print("0th Element:",arr[0])
print("1st Element:",arr[1])   


Array: [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
0th Element: [ 6  7  8  9 10]
1st Element: [1 2 3 4 5]


In [4]:
arr =np.array([[6, 7, 8, 9, 10],[1, 2, 3, 4, 5]])
print("Array:", arr)
arr[0][3] = 20
print("Updated Array:", arr)

Array: [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
Updated Array: [[ 6  7  8 20 10]
 [ 1  2  3  4  5]]


### Array Vs List

In [5]:
py_list = [1, 2, 3, 4, 5]
arr=np.array([py_list, py_list])
print("Array:", arr)
start = time.time()
print("Array:", arr*1000)
end = time.time()
print("Time taken:", end-start)
start = time.time()
print(py_list*1000)
end = time.time()
print("Time taken:", end-start)

Array: [[1 2 3 4 5]
 [1 2 3 4 5]]
Array: [[1000 2000 3000 4000 5000]
 [1000 2000 3000 4000 5000]]
Time taken: 0.00030684471130371094
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4,

### Array from scratch

In [6]:
arr =np.zeros((2, 3))
print(arr)
print("\n")
arr =np.ones((2, 3))
print(arr)
print("\n")
arr =np.full((2, 3), 5)
print(arr)
print("\n")
arr =np.random.random((2, 3))
print(arr)
print("\n")
arr =np.random.randint(0, 10, (2, 3))
print(arr)
print("\n")
seq_arr = np.arange(0, 10, 2)
print(seq_arr)
print("\n")
arr = np.eye(3)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]]


[[5 5 5]
 [5 5 5]]


[[0.54639773 0.70776222 0.00398712]
 [0.40716454 0.43957445 0.93355915]]


[[9 6 0]
 [1 9 3]]


[0 2 4 6 8]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Vectors, Matrix, Tensor

In [7]:
vector = np.array([1, 2, 3, 4, 5, 6])
print("Vector:", vector)
print("\n")
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:", matrix)
print("\n")
tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("Tensor:", tensor)

Vector: [1 2 3 4 5 6]


Matrix: [[1 2 3]
 [4 5 6]]


Tensor: [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Array Properties

In [8]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18]])
print("Array:", arr)
print("\n")
print("Shape:", arr.shape)
print("\n")
print("Size:", arr.size)
print("\n")
print("Data Type:", arr.dtype)
print("\n")
print("Dimension:", arr.ndim)
print("\n")
print("Item Size:", arr.itemsize)
print("\n")
print("Nbytes:", arr.nbytes)

Array: [[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]


Shape: (2, 9)


Size: 18


Data Type: int64


Dimension: 2


Item Size: 8


Nbytes: 144


### Array Reshaping

In [9]:
arr = np.arange(12)
print("Original Array:", arr)
print("\n")
reshaped_arr = arr.reshape(3,4)
print("Reshaped Array:", reshaped_arr)
print("\n")
flattened_arr = reshaped_arr.flatten()
print("Flattened Array:", flattened_arr)
print("\n")
ravelled_arr = reshaped_arr.ravel()
print("Ravelled Array:", ravelled_arr)
print("\n")
transposed_arr = reshaped_arr.T
print("Transposed Array:", transposed_arr)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


Reshaped Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


Ravelled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


Transposed Array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Array Indexing

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10])
print("array:",arr)
print("array with odd numbers:",arr[arr%2==1])
print("array with even numbers:",arr[arr%2==0])

array: [ 1  2  3  4  5  6  7  8  9 10]
array with odd numbers: [1 3 5 7 9]
array with even numbers: [ 2  4  6  8 10]


### Array Slicing 

In [11]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("array:",arr)
print("Basic slicing:",arr[2:7])
print("Step slicing:",arr[1:8:2])
print("Reverse slicing:",arr[::-1])
print("Reverse slicing with step:",arr[::-2])
print("Reverse slicing with step:",arr[-1:-5:-2])

array: [ 1  2  3  4  5  6  7  8  9 10]
Basic slicing: [3 4 5 6 7]
Step slicing: [2 4 6 8]
Reverse slicing: [10  9  8  7  6  5  4  3  2  1]
Reverse slicing with step: [10  8  6  4  2]
Reverse slicing with step: [10  8]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("Array:", arr)

Array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
